# Generated by Django 5.1.1 on 2024-10-29 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
