# Generated by Django 5.1.1 on 2024-10-29 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
