# Generated by Django 5.1.1 on 2024-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_post", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
