# Generated by Django 5.1.1 on 2024-10-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_post", "0004_alter_tag_options_tag_created_at_tag_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
