# Generated by Django 5.1.1 on 2024-10-29 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_post", "0007_alter_tag_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
