# Generated by Django 5.1.1 on 2024-10-29 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_post", "0008_alter_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="icon",
        ),
    ]
