# Generated by Django 5.1.1 on 2024-11-02 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_post", "0013_alter_comment_options_commentreply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentreply",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Comment Replies",
            },
        ),
    ]
