# Generated by Django 5.1.1 on 2024-11-04 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_post", "0016_likedcomments_comment_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LikedComments",
            new_name="LikedComment",
        ),
    ]
